In [2]:
import pandas as pd
import numpy as np
from numpy.linalg import norm
import random
import datetime as dt
from sklearn.metrics.pairwise import cosine_similarity
import itertools

image_emb = "C:\\Users\\aviel\\Desktop\\H&M project\\article_dictionary.csv"

desctiption_emb = "C:\\Users\\aviel\\Downloads\\desctiption_embeddings.csv"

prod_network = "C:\\Users\\aviel\\Desktop\\H&M project\\new_pn.csv"

In [3]:
desctiption_emb = pd.read_csv(desctiption_emb,index_col=False)
desctiption_emb.drop(["description","Description_new"],axis=1,inplace=True)
desctiption_emb.set_index('product_id', inplace=True)
desctiption_emb

,0,1,2,3,4,5,6,7,8,9,...,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023
product_id,,,,,,,,,,,,,,,,,,,,,
108775015,0.643704,-0.728313,-0.370916,0.930039,0.205670,-0.512119,-0.781456,0.846769,0.224285,0.927329,...,0.184097,-0.499265,0.154369,0.201446,-1.428334,1.050288,-0.188325,0.233521,-0.609104,0.525521
108775044,0.643703,-0.728313,-0.370917,0.930038,0.205671,-0.512120,-0.781456,0.846770,0.224286,0.927330,...,0.184097,-0.499264,0.154369,0.201446,-1.428334,1.050289,-0.188325,0.233522,-0.609104,0.525522
108775051,0.643703,-0.728313,-0.370917,0.930038,0.205671,-0.512120,-0.781456,0.846770,0.224286,0.927330,...,0.184097,-0.499264,0.154369,0.201446,-1.428334,1.050289,-0.188325,0.233522,-0.609104,0.525522
110065001,-0.688227,0.463673,-0.972770,0.495205,0.684199,0.604548,-0.995238,0.079121,-0.119942,1.173021,...,0.412209,-0.001696,-1.001149,1.065278,1.280330,1.151635,-1.661794,1.554372,-0.640086,1.515295
110065002,-0.688227,0.463673,-0.972770,0.495205,0.684199,0.604548,-0.995238,0.079121,-0.119942,1.173021,...,0.412209,-0.001696,-1.001149,1.065278,1.280330,1.151635,-1.661794,1.554372,-0.640086,1.515295
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
952267001,-1.602465,0.154406,-0.348622,0.881304,0.136543,0.057990,0.670265,-1.001950,-0.762636,-0.219616,...,0.562442,1.135879,-0.053923,1.210947,-0.327014,1.598899,-0.255556,0.439367,-1.028543,0.382494
952938001,0.241941,-0.197945,0.047121,0.453409,0.680855,-0.068687,-0.169899,0.186575,0.880405,0.422322,...,1.069627,1.141627,-0.185632,-0.028245,-0.098184,0.411468,-0.589029,1.043311,0.194269,0.335793
953450001,-0.744582,-0.203223,-1.332342,0.573179,0.149432,0.690094,0.415126,-1.298226,-0.387104,-0.586013,...,-0.926949,1.447537,-0.028138,1.073665,-1.368386,1.122979,-0.031763,0.745074,-0.822601,0.222582
953763001,0.260859,-0.362981,0.176343,0.321107,1.039282,0.413984,-0.710905,0.660509,0.960609,0.787137,...,-0.501578,0.718381,-0.136491,0.076062,0.260529,0.990542,0.302914,0.902546,-1.171218,1.038952
956217002,0.234185,-0.410371,-0.547763,0.734610,0.343378,-0.472451,0.695666,0.278675,0.601111,-0.236954,...,-0.382488,-0.340841,-1.020555,0.745414,0.122067,0.574844,0.586400,0.757711,-1.405221,-0.436263

In [4]:
images_df = pd.read_csv(image_emb)
images_df = images_df.rename(columns={'Unnamed: 0':'product_id'})
images_df.set_index('product_id', inplace=True)
images_df = images_df[images_df.index.isin(desctiption_emb.index)]
images_df

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
product_id,,,,,,,,,,,,,,,,,,,,,
663713001,0.615762,0.081262,0.516690,0.962563,0.924353,1.684056,0.687998,2.590135,1.345514,0.932243,...,0.722571,0.493880,1.514934,0.808707,0.175722,0.075635,2.540155,0.443045,0.144813,3.188583
541518023,1.309825,0.251596,2.650270,0.854556,0.499745,0.640864,0.317741,2.482037,1.334311,0.160331,...,0.805906,0.288806,1.909185,1.035806,0.235855,0.029039,1.755495,0.214506,0.068759,1.479373
505221004,0.643801,1.510989,0.000962,0.083988,0.042613,0.592353,0.222060,0.029552,3.803942,0.287578,...,4.138981,0.000378,1.651003,1.102987,0.376301,0.494068,0.162560,0.728679,0.592000,0.645665
685687003,0.416132,0.416597,0.004070,1.183370,0.039602,0.719203,0.099739,0.302293,2.071510,0.333582,...,0.368519,0.018202,1.945736,2.577750,0.341443,0.001426,0.894459,0.927478,0.049759,0.403430
685687004,0.665126,0.647309,0.020886,0.783940,0.089257,1.186417,0.576247,0.077178,2.789533,0.139908,...,0.337211,0.016081,1.795114,2.542928,0.192679,0.102081,0.774224,1.159667,0.022634,0.813263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930283003,1.844194,0.414522,0.649492,3.255364,0.313485,0.625589,0.189570,0.004084,2.670382,0.132117,...,1.265794,0.000000,2.334097,1.005270,0.220984,0.045704,0.552309,2.415084,0.237256,0.244044
913290001,0.602506,0.659813,0.933222,1.182815,0.431139,0.566961,0.090570,0.978365,2.587350,0.110887,...,0.644268,0.181295,1.941641,1.685020,0.456073,0.333248,1.587818,0.721524,0.145894,0.002023
860135008,3.103615,1.719505,0.165016,0.713198,0.004453,1.060009,0.903648,0.012053,3.356088,0.396377,...,0.684693,0.175806,2.183605,0.219923,0.060087,0.005731,0.513603,1.046612,0.099748,0.203500
539060028,0.588859,0.251988,0.035431,1.429736,0.010859,0.760527,0.398149,0.193703,2.337573,1.683170,...,0.083837,0.761508,4.536758,0.412522,1.514256,0.167885,0.260882,0.790517,0.283755,0.267347
533261032,0.162499,0.267408,1.060711,0.559430,0.007163,0.199093,0.000000,0.230638,1.305021,0.116497,...,0.181469,0.764973,0.635254,0.763182,1.424883,0.106377,0.900446,0.783379,0.035554,0.980919

In [5]:
network_df = pd.read_csv(prod_network,usecols=["a","b","count","cs"])
network_df = network_df[network_df["a"].isin(desctiption_emb.index) & network_df["b"].isin(desctiption_emb.index)]
#network_df = network_df.sort_values(by=["count","cs"],ascending=[False,False])
network_df

                  a          b  count        cs
0         684209013  688537011  10864  0.680656
1         689109001  692930001   8701  0.758178
2         689109003  692930003   8454  0.708184
3         706016001  706016002   8341  0.854595
4         501616007  507909001   8224  0.897532
...             ...        ...    ...       ...
42053305  557184001  617281002      1  0.550903
42053306  683176001  736111004      1  0.687260
42053307  683176001  736002002      1  0.591431
42053308  683176001  735945001      1  0.752114
42053309  709297003  866261002      1  0.530683

[41743180 rows x 4 columns]

In [315]:
articles_clusterCategory = np.genfromtxt(r"C:\Users\aviel\Desktop\H&M project\articles_clusterCategory.txt", delimiter=",")
articles_clusterCategory_df = pd.DataFrame(articles_clusterCategory).astype("int").rename(columns={0:"article_id",1:"Cluster"})
articles_clusterCategory_df = articles_clusterCategory_df[articles_clusterCategory_df["article_id"].isin(desctiption_emb.index)]
articles_cluster_dict = articles_clusterCategory_df.set_index("article_id").to_dict()
groups = articles_clusterCategory_df.groupby(["Cluster"])["article_id"].apply(list)

N_in_cluster = articles_clusterCategory_df["Cluster"].value_counts().to_dict()

In [10]:
articles_df = pd.read_csv(r"C:\Users\aviel\Desktop\H&M project\articles.csv")

n_rows = len(network_df)

def categorial_df():
    part_df = network_df[:n_rows]
    arts = list(set(list(part_df["a"])+list(part_df["b"])))
    categorial_df = articles_df.set_index("article_id").loc[arts].select_dtypes(include='object')
    
    all_articles = set(list(part_df['a'])+list(part_df['b']))
    test_articles = random.sample(all_articles, int(0.15*len(all_articles)))
    train_articles = list(set(all_articles)-set(test_articles))
    
    return categorial_df,test_articles,train_articles

categorial_df,test_products,train_products = categorial_df()
four_feature_df = categorial_df[["product_type_name","product_group_name","graphical_appearance_name","colour_group_name"]]
dummies_df = pd.get_dummies(four_feature_df)

C:\Users\aviel\AppData\Local\Temp\ipykernel_18256\3299929561.py:11: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  test_articles = random.sample(all_articles, int(0.15*len(all_articles)))

In [18]:
def prepDatasets_featureNaive(test_products,train_products):
    train_df = dummies_df.loc[train_products]
    train_mat = train_df.to_numpy()
    test_df = dummies_df.loc[test_products]
    test_mat = test_df.to_numpy()
    # calculating Cosine similarity of all imagaes in test against all images in train
    a = test_mat.dot(train_mat.T)
    b = (norm(test_mat,axis=1,keepdims=True)*norm(train_mat.T,axis=0,keepdims=True))
    cosine_sim = a/b
    # creating a cosine similarity dataframe
    cosine_sim_df = pd.DataFrame(cosine_sim,columns=train_df.index)
    cosine_sim_df['article_id'] = test_df.index
    cosine_sim_df.set_index('article_id',inplace=True)

    #adding the maximal similarity column
    cosine_sim_df['max_sim'] = cosine_sim_df.idxmax(axis=1)   #max.index(axis=1)

    # # apply the function to each row to create the new column
    #cosine_sim_df['top_5_prod'] = cosine_sim_df[cosine_sim_df.columns[0:-1]].apply(top_5, axis=1)

    return cosine_sim_df
features_similarity = prepDatasets_featureNaive(test_products,train_products)

MemoryError: Unable to allocate 10.1 GiB for an array with shape (15486, 87757) and data type float64

In [17]:
cosine_sim_df

NameError: name 'cosine_sim_df' is not defined

## cosine similarity dataframe preparation function

In [316]:
# define a function to find the top 5 values in a row
def top_5(row):
    return row.nlargest(5).index.tolist()

def prepDatasets_images(test_products,train_products):
    train_df = images_df.loc[train_products]
    train_mat = train_df.to_numpy()
    test_df = images_df.loc[test_products]
    test_mat = test_df.to_numpy()
    # calculating Cosine similarity of all imagaes in test against all images in train
    a = test_mat.dot(train_mat.T)
    b = (norm(test_mat,axis=1,keepdims=True)*norm(train_mat.T,axis=0,keepdims=True))
    cosine_sim = a/b
    # creating a cosine similarity dataframe
    cosine_sim_df = pd.DataFrame(cosine_sim,columns=train_df.index)
    cosine_sim_df['prod_id'] = test_df.index
    cosine_sim_df.set_index('prod_id',inplace=True)

    #adding the maximal similarity column
    cosine_sim_df['max_sim'] = cosine_sim_df.idxmax(axis=1)   #max.index(axis=1)

    # # apply the function to each row to create the new column
    cosine_sim_df['top_5_prod'] = cosine_sim_df[cosine_sim_df.columns[0:-1]].apply(top_5, axis=1)

    return cosine_sim_df

def prepDatasets_desctiption(test_products,train_products):
    train_df = desctiption_emb.loc[train_products]
    train_mat = train_df.to_numpy()
    test_df = desctiption_emb.loc[test_products]
    test_mat = test_df.to_numpy()
    # calculating Cosine similarity of all imagaes in test against all images in train
    a = test_mat.dot(train_mat.T)
    b = (norm(test_mat,axis=1,keepdims=True)*norm(train_mat.T,axis=0,keepdims=True))
    cosine_sim = a/b
    # creating a cosine similarity dataframe
    cosine_sim_df = pd.DataFrame(cosine_sim,columns=train_df.index)
    cosine_sim_df['prod_id'] = test_df.index
    cosine_sim_df.set_index('prod_id',inplace=True)

    #adding the maximal similarity column
    cosine_sim_df['max_sim'] = cosine_sim_df.idxmax(axis=1)   #max.index(axis=1)

    # # apply the function to each row to create the new column
    cosine_sim_df['top_5_prod'] = cosine_sim_df[cosine_sim_df.columns[0:-1]].apply(top_5, axis=1)

    return cosine_sim_df

In [ ]:
pr

## Recommendation functions

In [346]:
#sorted_net_by_count = network_df.sort_values(by=['count'],ascending=False)

def get_rec_prods_A(p_new, rec_num, df):
    p_old = df.loc[p_new,'max_sim']
    five_closest = list(set(itertools.chain(*train_data[(train_data.a==p_old)|(train_data.b==p_old)].sort_values(
    by=['count'],ascending=False)[0:5][["a","b"]].to_numpy()))-set([p_old]))
    
    return five_closest

def get_rec_prods_B(p_new, rec_num,df):
    p_old_list = df.loc[p_new,'top_5_prod']
    closests = []
    max_a =0
    max_b=0
    for p in p_old_list:
        try :
            if len(train_data[(train_data.a==p)]['count'])>0:
                max_a = train_data[(train_data.a==p)]['count'].max()
                prod_a = train_data[(train_data.a == p)&(train_data["count"] == max_a)]["b"].values[0]
            if len(train_data[(train_data.b==p)]['count'])>0:
                max_b = train_data[(train_data.b==p)]['count'].max()
                prod_b = train_data[(train_data.b == p)&(train_data["count"] == max_b)]["a"].values[0]
            if max_a>max_b:
                closests.append(prod_a)
            else:
                closests.append(prod_b)
        except: 
            pass
    return closests

def naive_recomendation(rec_num):
    naive_prods = []
    for i in range(5):
        naive_prods.append(int(train_data.iloc[i]["a"]))
        naive_prods.append(int(train_data.iloc[i]["b"]))
    return list(pd.unique(naive_prods)[0:rec_num])

    
def get_actual_closest(p_new,rec_num):
    return list(set(itertools.chain(*network_df[(network_df.a==p_new)|(network_df.b==p_new)].sort_values(
        by=['count'],ascending=False)[0:rec_num][["a","b"]].to_numpy()))-set([p_new]))

## Evaluation Functions

In [347]:
def IoU(a, b):
    intersection = list(set(a) & set(b)) 
    union = set(a + b)
    if (len(union)>0):
        return (len(intersection)/len(union))
    return 0

IoU([1,2,3,4,8], [1,2,5,6,7,3,4])

def atLeastOneShot(a, b):
    intersection = list(set(a) & set(b))
    return (len(intersection)>0)

atLeastOneShot([1,2,3,4,8], [1,2,5,6,7,3,4])

def numOfSuccesses(a,b):
    intersection = list(set(a) & set(b))
    return (len(intersection))
numOfSuccesses([1,2,3,4,8], [1,2,5,6,7,3,4])

4

In [348]:
def train_df(df,train_products):
    return df[(df["a"].isin(train_products))&(df["b"].isin(train_products))]

# testing all the data

In [398]:
%%time
#n = len(network_df)
k=5
res_df = pd.DataFrame()
#set(list(network_df[0:n]['a'])+list(network_df[0:n]['b']))
prod_list = set(list(network_df['a'])+list(network_df['b']))
for i in range(5):
    test_products=test_products = random.sample(prod_list, int(0.15*len(prod_list)))
    train_products = list(set(prod_list)-set(test_products))
    train_data = train_df(network_df,train_products)
    
    
    train_data["cluster_a"] = train_data["a"].apply(get_cluster)
    train_data["cluster_b"] = train_data["b"].apply(get_cluster)
    dict_a = train_data[["a"]].groupby("a").size().to_dict()
    dict_b = train_data[["b"]].groupby("b").size().to_dict()
    
    def get_norm(x):
        try :
            a = dict_a[x[0]]
        except :
            a = 0
        try :
            b = dict_b[x[1]]
        except :
            b = 0
        return (x[2]/(a+b))/(N_in_cluster[x[3]]+N_in_cluster[x[4]])

    train_data["norm_count"] = train_data[["a","b","count","cluster_a",'cluster_b']].apply(lambda x : get_norm(x),axis=1)
    best_for_cluster = []
    for num in range(43):

        best_for_cluster.append(list(set(itertools.chain(*(
        train_data[(train_data["cluster_a"] == num)|(train_data["cluster_b"] == num)].sort_values(
            by="norm_count")[:5][["a","b"]].values))).intersection(groups[num])))

    groups_df = groups.reset_index()
    groups_df["reccomends_per_cluster"] = best_for_cluster
    groups_df.set_index("Cluster",inplace=True)

    cosine_sim_df_image = prepDatasets_images(test_products,train_products)
    cosine_sim_df_desctiption = prepDatasets_desctiption(test_products,train_products)
    
    naive_recommendations = naive_recomendation(5)
    res = []
    for row in articles_clusterCategory_df[articles_clusterCategory_df["article_id"].isin(test_products)].iterrows():

        p = row[1]["article_id"]

        actual = get_actual_closest(p,5)

        clustering_pred = groups_df.loc[row[1]["Cluster"]]["reccomends_per_cluster"]
        cluster_IOU = IoU(clustering_pred,actual)
        cluster_atLeastOneShot = atLeastOneShot(clustering_pred,actual)
        cluster_numOfSuccesses = numOfSuccesses(clustering_pred,actual)

        naive_IoU = IoU(naive_recommendations,actual)
        One_shot_naive = atLeastOneShot(naive_recommendations, actual)
        numSuc_naive = numOfSuccesses(naive_recommendations,actual)

        #image
        A_image = get_rec_prods_A(p,5,cosine_sim_df_image)
        A_IoU_image = IoU(A_image,actual)
        One_shot_A_image = atLeastOneShot(A_image, actual)
        numSuc_A_image = numOfSuccesses(A_image,actual)

        B_image = get_rec_prods_B(p,5,cosine_sim_df_image)
        B_IoU_image = IoU(B_image,actual)
        One_shot_B_image = atLeastOneShot(B_image, actual)
        numSuc_B_image = numOfSuccesses(B_image,actual)

        #desctiption
        A_desctiption = get_rec_prods_A(p,5,cosine_sim_df_desctiption)
        A_IoU_desctiption = IoU(A_desctiption,actual)
        One_shot_A_desctiption = atLeastOneShot(A_desctiption, actual)
        numSuc_A_desctiption = numOfSuccesses(A_desctiption,actual)

        B_desctiption = get_rec_prods_B(p,5,cosine_sim_df_desctiption)
        B_IoU_desctiption = IoU(B_desctiption,actual)
        One_shot_B_desctiption = atLeastOneShot(B_desctiption, actual)
        numSuc_B_desctiption = numOfSuccesses(B_desctiption,actual)

        res.append({"cluster_IOU":cluster_IOU,"cluster_atLeastOneShot":cluster_atLeastOneShot,"cluster_numOfSuccesses":cluster_numOfSuccesses,
            "naive_IoU":naive_IoU,"One_shot_naive":One_shot_naive,"numSuc_naive" : numSuc_naive,

            "A_IoU_image" :  A_IoU_image,"One_shot_A_image" :  One_shot_A_image ,'numSuc_A_image' :numSuc_A_image,
            "B_IoU_image" :  B_IoU_image,'One_shot_B_image' :  One_shot_B_image,"numSuc_B_image" : numSuc_B_image,

            "A_IoU_desctiption" : A_IoU_desctiption,'One_shot_A_desctiption' : One_shot_A_desctiption,'numSuc_A_desctiption':numSuc_A_desctiption,
            "B_IoU_desctiption" : B_IoU_desctiption,"One_shot_B_desctiption":  One_shot_B_desctiption,"numSuc_B_desctiption" : numSuc_B_desctiption})


    res_df[i] = (pd.DataFrame(res).mean())
    print(res_df)
res_df

KeyboardInterrupt:

In [356]:
df_mean_sd = pd.concat([res_df.mean(axis=1),res_df.std(axis=1)],axis=1)
df_mean_sd.columns = ['mean','sd']
df_mean_sd

                            mean        sd
cluster_IOU             0.181726  0.068686
cluster_atLeastOneShot  0.425000  0.068465
cluster_numOfSuccesses  0.775000  0.346861
naive_IoU               0.019841  0.022139
One_shot_naive          0.100000  0.104583
numSuc_naive            0.150000  0.162980
A_IoU_image             0.092292  0.084573
One_shot_A_image        0.250000  0.153093
numSuc_A_image          0.400000  0.285044
B_IoU_image             0.125060  0.071857
One_shot_B_image        0.350000  0.223607
numSuc_B_image          0.650000  0.335410
A_IoU_desctiption       0.097738  0.042632
One_shot_A_desctiption  0.275000  0.104583
numSuc_A_desctiption    0.350000  0.136931
B_IoU_desctiption       0.154286  0.072336
One_shot_B_desctiption  0.400000  0.205396
numSuc_B_desctiption    0.725000  0.323554